footprint: [[0.28,0.24],[-0.28,0.24],[-0.28,-0.24],[0.28,-0.24]]
footprint_padding: 0.1

min_obstacle_height: 0.05
max_obstacle_height: 0.3

#障碍物层
obstacles_layer:
  enabled: true
  track_unknown_space: true
  max_obstacle_height: 0.3
  min_obstacle_height: 0.05
  footprint_clearing_enabled: true
  obstacle_range: 7.5
  raytrace_range: 8

  observation_sources: front_scan  
  front_scan: 
    sensor_frame: laser_fix_link
    data_type: LaserScan
    clearing: true
    marking: true
    topic: /scan  
    max_obstacle_height: 0.3
    min_obstacle_height: 0.05
    obstacle_range: 7.5
    raytrace_range: 8


local_inflation_layer:
  enabled: true
  inflation_radius: 0.15
  inflate_unknown: true

global_inflation_layer:
  inflation_radius: 0.2
  inflate_unknown: false


static_layer:
  enabled: true
  track_unknown_space: false
  lethal_cost_threshold: 100 




