#controller_frequency: 5.0
recovery_behaviour_enabled: false

NavfnROS:
  allow_unknown: false
  default_tolerance: 0.0
  planner_window_x: 0.0
  planner_window_y: 0.0


GlobalPlanner:
  old_navfn_behavior: false 
  allow_unknown: false 
  use_dijkstra: true 
  use_quadratic: true 
  use_grid_path: false 

  default_tolerance: 0.0 
  
