odom_frame: /odom
base_link_frame: /base_link
world_frame: /odom

two_d_mode: true

frequency: 20
publish_acceleration: false

publish_tf: true

odom0: /scholar_r500_bringup/scholar_r500/odom
odom0_config: [true, true, false,
               false, false, true,
               true, false, false,
               false, false, true,
               false, false, false]
#odom0_differential: true
#odom0_relative: true
odom0_queue_size: 20

imu0: /scholar_r500_imu_driver/scholar_imu/imu_data
imu0_config: [false, false, false,
              true, true, true,
              false, false, false,
              true, true, true,
              true, true, false]
#imu0_differential: true
imu0_relative: true
imu0_queue_size: 20
imu0_remove_gravitational_acceleration: true
gravitational_acceleration: 9.805

use_control: true
stamped_control: false
control_timeout: 0.05
control_config: [true,  false, false,
                                  false, false, true]
acceleration_limits: [1.0, 0.0, 0.0, 0.0, 0.0, 2.0]
deceleration_limits: [1.0, 0.0, 0.0, 0.0, 0.0, 2.0]
acceleration_gains: [0.5, 0.0, 0.0,  0.0, 0.0, 0.5]
deceleration_gains: [0.5, 0.0, 0.0,  0.0, 0.0, 0.5]
smooth_lagged_data: true 
history_length: 2.0
dynamic_process_noise_covariance: false
