local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 10.0 #代价地图的更新频率
  publish_frequency: 5.0 #代价地图的发布频率
  rolling_window: true #是否使用动态窗口
  width: 2.0 #代价地图的宽度
  height: 2.0 #代价地图的高度
  resolution: 0.05 #代价地图的精度，即每个网格的尺寸
  origin_x: 0  #代价地图x坐标在世界坐标系中的位置
  origin_y: 0  #代价地图y坐标在世界坐标系中的位置
  transform_tolerance: 0.5  #等待tf转换的时间

  plugins:
    - {name: obstacles_layer,           type: "costmap_2d::ObstacleLayer"}
    - {name: local_inflation_layer,     type: "costmap_2d::InflationLayer"}
