local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 5.0
  rolling_window: true
  width: 2.0
  height: 2.0
  resolution: 0.05
  origin_x: 0
  origin_y: 0
  transform_tolerance: 0.5

  plugins:
    - {name: obstacles_layer,           type: "costmap_2d::ObstacleLayer"}
    - {name: local_inflation_layer,     type: "costmap_2d::InflationLayer"}
