#base_local_planner: dwa_local_planner/DWAPlannerROS
base_local_planner: base_local_planner/TrajectoryPlannerROS
#base_local_planner: teb_local_planner/TebLocalPlannerROS
#base_global_planner: global_planner/GlobalPlanner
base_global_planner: navfn/NavfnROS

shutdown_costmaps: false
controller_frequency: 10.0
controller_patience: 4.0

planner_frequency: 1.0
planner_patience: 5.0
  
max_planning_retries: -1

oscillation_timeout: 5.0
oscillation_distance: 0.2
conservative_reset:
   reset_distance: 1.0
 
recovery_behavior_enabled: true
clearing_rotation_allowed: false

